adjective = input("Please enter an adjective: ")
noun = input("Please enter a noun: ")
verb = input("Please enter a verb ending in -ed: ")
print("\nYour MadLib:")
print("The", adjective, noun, verb, "over the lazy brown dog.")